import type { Product, Settings } from "@/lib/types";

const now = new Date();

export const defaultProducts: Product[] = [
  {
    productId: "ayam-lidi",
    name: "Ayam Lidi",
    basePrice: 3,
    withCheesePrice: 3,
    hasCheeseOption: true,
    hasPowderOption: true,
    cheeseAffectsPrice: false,
    imageUrl: null,
    imagePath: null,
    imageSize: null,
    isAvailable: true,
    isArchived: false,
    archivedAt: null,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    productId: "ayam-gunting",
    name: "Ayam Gunting",
    basePrice: 10,
    withCheesePrice: 12,
    hasCheeseOption: true,
    hasPowderOption: true,
    cheeseAffectsPrice: true,
    imageUrl: null,
    imagePath: null,
    imageSize: null,
    isAvailable: true,
    isArchived: false,
    archivedAt: null,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    productId: "sosej-cheese",
    name: "Sosej Cheese",
    basePrice: 5,
    withCheesePrice: null,
    hasCheeseOption: false,
    hasPowderOption: true,
    cheeseAffectsPrice: false,
    imageUrl: null,
    imagePath: null,
    imageSize: null,
    isAvailable: true,
    isArchived: false,
    archivedAt: null,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
];

export const defaultSettings: Settings = {
  stallName: "Ayam Gunting Cheese",
  posName: "AGCPOS",
  logoText: "AGC",
  logoUrl: null,
  logoPath: null,
  themeMode: "system",
  accentTheme: "yellow-black-red",
  buttonSize: "large",
  enabledPaymentMethods: {
    cash: true,
    qrDuitNow: true,
    bankTransfer: true,
  },
  confirmBeforeLogout: true,
  confirmBeforeCancel: true,
  askPaymentMethodBeforeComplete: true,
  autoClearCartAfterSubmit: true,
  dailyOrderReset: true,
  updatedAt: now,
};
